// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxRwkiq2eJnd3HHUmB7CF3tTmWNZtOcc',
    appId: '1:905182025124:android:89c4fbfe1dc05df9a01d31',
    messagingSenderId: '905182025124',
    projectId: 'aquasense-e5487',
    databaseURL: 'https://aquasense-e5487-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquasense-e5487.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWpULOvvZV_81T_1GKTw9UMibk35Zba-k',
    appId: '1:905182025124:ios:8ba1ba6eb79b6823a01d31',
    messagingSenderId: '905182025124',
    projectId: 'aquasense-e5487',
    databaseURL: 'https://aquasense-e5487-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquasense-e5487.firebasestorage.app',
    iosBundleId: 'com.example.aquaSense',
  );
}
